#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# SalesLens — Clean teardown of provisioned infrastructure
#
# Reads the resource file created by provision-spot.sh and removes:
#   - EC2 spot instance (cancels spot request + terminates)
#   - Security group
#   - IAM role, policy, and instance profile
#   - Optionally: S3 bucket and all objects (with --delete-data)
#
# Usage:
#   ./teardown.sh <resource-file>                 # keep S3 data
#   ./teardown.sh <resource-file> --delete-data   # also delete bucket + objects
#
# The resource file is saleslens-resources-<suffix>.env generated by
# provision-spot.sh.
# ---------------------------------------------------------------------------
set -euo pipefail

RESOURCE_FILE="${1:-}"
DELETE_DATA=false

for arg in "$@"; do
  case "$arg" in
    --delete-data) DELETE_DATA=true ;;
  esac
done

log()  { echo "[saleslens-teardown] $*"; }
fail() { echo "[saleslens-teardown] ERROR: $*" >&2; exit 1; }

[[ -z "$RESOURCE_FILE" ]] && fail "Usage: ./teardown.sh <resource-file> [--delete-data]"
[[ -f "$RESOURCE_FILE" ]] || fail "Resource file not found: ${RESOURCE_FILE}"

# shellcheck source=/dev/null
source "$RESOURCE_FILE"

command -v aws >/dev/null 2>&1 || fail "aws CLI not found"

log "Tearing down SalesLens resources (suffix: ${RANDOM_SUFFIX:-unknown})..."

# ── Cancel spot request if persistent ──────────────────────────────────────
log "Checking for active spot requests..."
SPOT_REQUEST_ID=$(aws ec2 describe-spot-instance-requests \
  --region "$REGION" \
  --filters "Name=instance-id,Values=${INSTANCE_ID}" \
  --query 'SpotInstanceRequests[0].SpotInstanceRequestId' \
  --output text 2>/dev/null || echo "None")

if [[ -n "$SPOT_REQUEST_ID" && "$SPOT_REQUEST_ID" != "None" ]]; then
  log "Cancelling spot request: ${SPOT_REQUEST_ID}..."
  aws ec2 cancel-spot-instance-requests \
    --region "$REGION" \
    --spot-instance-request-ids "$SPOT_REQUEST_ID" >/dev/null 2>&1 || true
fi

# ── Terminate instance ─────────────────────────────────────────────────────
log "Terminating instance: ${INSTANCE_ID}..."
aws ec2 terminate-instances \
  --region "$REGION" \
  --instance-ids "$INSTANCE_ID" >/dev/null 2>&1 || true

log "Waiting for instance to terminate..."
aws ec2 wait instance-terminated \
  --region "$REGION" \
  --instance-ids "$INSTANCE_ID" 2>/dev/null || true

# ── Remove IAM role, policy, and instance profile ──────────────────────────
log "Cleaning up IAM resources..."

# Detach role from instance profile
aws iam remove-role-from-instance-profile \
  --instance-profile-name "$PROFILE_NAME" \
  --role-name "$ROLE_NAME" 2>/dev/null || true

# Delete instance profile
aws iam delete-instance-profile \
  --instance-profile-name "$PROFILE_NAME" 2>/dev/null || true

# Delete inline policy
aws iam delete-role-policy \
  --role-name "$ROLE_NAME" \
  --policy-name "saleslens-s3-access" 2>/dev/null || true

# Delete role
aws iam delete-role \
  --role-name "$ROLE_NAME" 2>/dev/null || true

log "IAM resources cleaned up."

# ── Delete security group ──────────────────────────────────────────────────
log "Deleting security group: ${SG_ID}..."
# May need a few seconds after instance termination
for i in $(seq 1 6); do
  if aws ec2 delete-security-group \
    --region "$REGION" \
    --group-id "$SG_ID" 2>/dev/null; then
    break
  fi
  sleep 5
done
log "Security group deleted."

# ── S3 bucket ──────────────────────────────────────────────────────────────
if $DELETE_DATA; then
  log "Emptying and deleting S3 bucket: ${BUCKET_NAME}..."
  aws s3 rm "s3://${BUCKET_NAME}" --recursive 2>/dev/null || true
  aws s3api delete-bucket \
    --bucket "$BUCKET_NAME" \
    --region "$REGION" 2>/dev/null || true
  log "S3 bucket deleted."
else
  log "S3 bucket '${BUCKET_NAME}' preserved (use --delete-data to remove)."
fi

# ── Done ───────────────────────────────────────────────────────────────────
cat <<EOF

============================================================
  SalesLens teardown complete
============================================================

  Terminated:  ${INSTANCE_ID}
  Removed:     ${SG_NAME} (security group)
  Removed:     ${ROLE_NAME} (IAM role + profile)
  S3 Bucket:   ${BUCKET_NAME} $(${DELETE_DATA} && echo "[DELETED]" || echo "[PRESERVED]")

  You can safely delete the resource file:
    rm ${RESOURCE_FILE}

============================================================
EOF
