#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# CIE — Clean teardown of provisioned infrastructure
#
# Reads the resource file created by provision-spot.sh and removes:
#   - EC2 spot instance (cancels spot request + terminates)
#   - SSM parameter (/cie/private-ip)
#   - Optionally: security group, IAM, S3 (with --delete-all)
#
# Reused resources (SG, IAM, EBS) are NOT deleted by default.
#
# Usage:
#   ./teardown.sh <resource-file>                 # instance + SSM only
#   ./teardown.sh <resource-file> --delete-all    # also SG, IAM, S3, EBS
#
# The resource file is cie-resources-<suffix>.env generated by
# provision-spot.sh.
# ---------------------------------------------------------------------------
set -euo pipefail

RESOURCE_FILE="${1:-}"
DELETE_ALL=false

for arg in "$@"; do
  case "$arg" in
    --delete-all) DELETE_ALL=true ;;
  esac
done

log()  { echo "[cie-teardown] $*"; }
fail() { echo "[cie-teardown] ERROR: $*" >&2; exit 1; }

[[ -z "$RESOURCE_FILE" ]] && fail "Usage: ./teardown.sh <resource-file> [--delete-all]"
[[ -f "$RESOURCE_FILE" ]] || fail "Resource file not found: ${RESOURCE_FILE}"

# shellcheck source=/dev/null
source "$RESOURCE_FILE"

command -v aws >/dev/null 2>&1 || fail "aws CLI not found"

log "Tearing down CIE resources..."

# ── Cancel spot request if persistent ──────────────────────────────────────
log "Checking for active spot requests..."
SPOT_REQUEST_ID=$(aws ec2 describe-spot-instance-requests \
  --region "$REGION" \
  --filters "Name=instance-id,Values=${INSTANCE_ID}" \
  --query 'SpotInstanceRequests[0].SpotInstanceRequestId' \
  --output text 2>/dev/null || echo "None")

if [[ -n "$SPOT_REQUEST_ID" && "$SPOT_REQUEST_ID" != "None" ]]; then
  log "Cancelling spot request: ${SPOT_REQUEST_ID}..."
  aws ec2 cancel-spot-instance-requests \
    --region "$REGION" \
    --spot-instance-request-ids "$SPOT_REQUEST_ID" >/dev/null 2>&1 || true
fi

# ── Detach EBS data volume (if attached) ─────────────────────────────────
if [[ -n "${EBS_VOLUME_ID:-}" ]]; then
  log "Detaching EBS data volume: ${EBS_VOLUME_ID}..."
  aws ec2 detach-volume \
    --region "$REGION" \
    --volume-id "$EBS_VOLUME_ID" \
    --force >/dev/null 2>&1 || true

  if $DELETE_ALL; then
    log "Waiting for volume to detach..."
    aws ec2 wait volume-available \
      --region "$REGION" \
      --volume-ids "$EBS_VOLUME_ID" 2>/dev/null || true
    log "Deleting EBS volume: ${EBS_VOLUME_ID}..."
    aws ec2 delete-volume \
      --region "$REGION" \
      --volume-id "$EBS_VOLUME_ID" 2>/dev/null || true
  else
    log "EBS volume ${EBS_VOLUME_ID} detached but preserved (use --delete-all to remove)."
  fi
fi

# ── Terminate instance ─────────────────────────────────────────────────────
log "Terminating instance: ${INSTANCE_ID}..."
aws ec2 terminate-instances \
  --region "$REGION" \
  --instance-ids "$INSTANCE_ID" >/dev/null 2>&1 || true

log "Waiting for instance to terminate..."
aws ec2 wait instance-terminated \
  --region "$REGION" \
  --instance-ids "$INSTANCE_ID" 2>/dev/null || true

# ── Remove SSM parameter (IP is instance-specific, always delete) ──────────
log "Removing SSM parameter /cie/private-ip..."
aws ssm delete-parameter \
  --region "$REGION" \
  --name "/cie/private-ip" 2>/dev/null || true

# ── Remove SSM secrets (only with --delete-all) ──────────────────────────
if $DELETE_ALL; then
  log "Removing SSM secret parameters..."
  for param in /cie/secrets/postgres-password /cie/secrets/jwt-secret \
               /cie/secrets/deepgram-api-key /cie/secrets/openai-api-key \
               /cie/config/s3-bucket; do
    aws ssm delete-parameter \
      --region "$REGION" \
      --name "$param" 2>/dev/null || true
  done
  log "SSM secret parameters deleted."
else
  log "SSM secrets preserved (use --delete-all to remove)."
fi

# ── Conditionally delete shared resources ────────────────────────────────────
if $DELETE_ALL; then
  # IAM
  if [[ -n "${ROLE_NAME:-}" ]]; then
    log "Cleaning up IAM resources..."
    aws iam remove-role-from-instance-profile \
      --instance-profile-name "$PROFILE_NAME" \
      --role-name "$ROLE_NAME" 2>/dev/null || true
    aws iam delete-instance-profile \
      --instance-profile-name "$PROFILE_NAME" 2>/dev/null || true
    aws iam delete-role-policy \
      --role-name "$ROLE_NAME" \
      --policy-name "cie-s3-access" 2>/dev/null || true
    aws iam delete-role-policy \
      --role-name "$ROLE_NAME" \
      --policy-name "cie-s3-ssm-access" 2>/dev/null || true
    aws iam delete-role \
      --role-name "$ROLE_NAME" 2>/dev/null || true
    log "IAM resources cleaned up."
  fi

  # Security group
  log "Deleting security group: ${SG_ID}..."
  for i in $(seq 1 6); do
    if aws ec2 delete-security-group \
      --region "$REGION" \
      --group-id "$SG_ID" 2>/dev/null; then
      break
    fi
    sleep 5
  done

  # S3
  log "Emptying and deleting S3 bucket: ${BUCKET_NAME}..."
  aws s3 rm "s3://${BUCKET_NAME}" --recursive 2>/dev/null || true
  aws s3api delete-bucket \
    --bucket "$BUCKET_NAME" \
    --region "$REGION" 2>/dev/null || true
  log "S3 bucket deleted."
else
  log "Shared resources preserved (SG, IAM, S3, EBS). Use --delete-all to remove."
fi

# ── Done ───────────────────────────────────────────────────────────────────
cat <<EOF

============================================================
  CIE teardown complete
============================================================

  Terminated:  ${INSTANCE_ID}
  SSM IP:      /cie/private-ip [DELETED]
  SSM secrets: $($DELETE_ALL && echo "[DELETED]" || echo "[PRESERVED]")
  EBS volume:  ${EBS_VOLUME_ID:-none} $(if [[ -n "${EBS_VOLUME_ID:-}" ]]; then $DELETE_ALL && echo "[DELETED]" || echo "[PRESERVED]"; fi)
  S3 Bucket:   ${BUCKET_NAME} $($DELETE_ALL && echo "[DELETED]" || echo "[PRESERVED]")
  SG / IAM:    $($DELETE_ALL && echo "[DELETED]" || echo "[PRESERVED]")

  You can safely delete the resource file:
    rm ${RESOURCE_FILE}

============================================================
EOF
