"""Alembic environment configuration for SalesLens.

This module is invoked by Alembic for both ``online`` (connected to a live
database) and ``offline`` (SQL script generation) migrations.  It imports
the SQLAlchemy ``Base.metadata`` from the application's model layer so that
``--autogenerate`` can detect schema changes.
"""

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# ---------------------------------------------------------------------------
# Ensure the backend package is importable.  When Alembic is invoked from
# the repository root (``alembic -c backend/alembic.ini ...``), the
# ``backend/`` directory may not be on sys.path.
# ---------------------------------------------------------------------------
_backend_dir = str(Path(__file__).resolve().parent.parent)
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

# ---------------------------------------------------------------------------
# Application imports — these must come AFTER the sys.path adjustment.
# ---------------------------------------------------------------------------
from app.config import settings  # noqa: E402

# Import ALL models so that Base.metadata is fully populated before
# Alembic inspects it for autogenerate.  The order does not matter as
# long as every model module is imported.
from app.models.base import Base  # noqa: E402
from app.models.tenant import Tenant  # noqa: E402
from app.models.user import User  # noqa: E402
from app.models.call import Call  # noqa: E402
from app.models.quality import QualityParameter, CallQualityScore  # noqa: E402
from app.models.intent import IntentSignal, CallIntentSignal  # noqa: E402
from app.models.persona import PersonaType, CallPersona  # noqa: E402
from app.models.action_item import ActionItem  # noqa: E402
from app.models.report import WeeklyReport  # noqa: E402
from app.models.integration import Integration, ApiKey  # noqa: E402

# ---------------------------------------------------------------------------
# Alembic Config object — provides access to values in alembic.ini.
# ---------------------------------------------------------------------------
config = context.config

# Set the SQLAlchemy URL from application settings so that it does not
# need to be duplicated in alembic.ini.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Configure Python logging from the alembic.ini [loggers] section.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The target metadata that Alembic uses for --autogenerate.
target_metadata = Base.metadata


# ---------------------------------------------------------------------------
# Migration runners
# ---------------------------------------------------------------------------


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This generates SQL statements without connecting to the database.
    Useful for reviewing migration SQL before applying it.

    Invoked by::

        alembic upgrade head --sql
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    Creates an Engine and associates a connection with the migration
    context.  This is the normal mode used by ``alembic upgrade head``.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            # Include object name in autogenerated migration names
            # for better readability.
            include_name=lambda name, type_, parent_names: True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
